version: "3"

x-db-base: &db-base
  image: postgres:17.2
  environment:
    POSTGRES_DB: keycloak
    POSTGRES_USER: db_admin
    POSTGRES_PASSWORD: db_password
  networks:
    keycloak-network:

x-keycloak-env: &keycloak-env
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/privkey.pem
  KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/fullchain.pem
  KC_DB: postgres
  KC_DB_USERNAME: db_admin
  KC_DB_PASSWORD: db_password
  KC_HOSTNAME: 0.0.0.0
  KC_HOSTNAME_PORT: 8443
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
  KC_FEATURES: organization

services:
  nginx:
    depends_on:
      - keycloak
      - first-provider
      - second-provider
    image: nginx:latest
    container_name: keycloak-proxy
    ports:
      - "8443:8443" # プロキシがリッスンするポート
    networks:
      - keycloak-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .cert:/etc/nginx/certs

  keycloak:
    depends_on:
      - keycloak-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      <<: *keycloak-env
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
    networks:
      keycloak-network:
        aliases:
          - master.keycloak.local
    command: ["start", "--optimized", "--hostname=master.keycloak.local"]

  keycloak-db:
    <<: *db-base
    container_name: keycloak-db
    volumes:
      - .data/keycloak-db:/var/lib/postgresql/data

  first-provider:
    depends_on:
      - first-provider-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: first-provider
    environment:
      <<: *keycloak-env
      KC_DB_URL: jdbc:postgresql://first-provider-db:5432/keycloak
    networks:
      keycloak-network:
        aliases:
          - first.keycloak.local
    command: ["start", "--optimized", "--hostname=first.keycloak.local"]

  first-provider-db:
    <<: *db-base
    container_name: first-provider-db
    volumes:
      - .data/first-provider-db:/var/lib/postgresql/data

  second-provider:
    depends_on:
      - second-provider-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: second-provider
    environment:
      <<: *keycloak-env
      KC_DB_URL: jdbc:postgresql://second-provider-db:5432/keycloak
    networks:
      keycloak-network:
        aliases:
          - second.keycloak.local
    command: ["start", "--optimized", "--hostname=second.keycloak.local"]

  second-provider-db:
    <<: *db-base
    container_name: second-provider-db
    volumes:
      - .data/second-provider-db:/var/lib/postgresql/data

networks:
  keycloak-network:
    driver: bridge
